---
- hosts: configure
  become: true
  vars_files:
    - vars/vars.yaml

  handlers:
    - name: Reload sysctl configuration
      command: sysctl --system

  tasks:
    - name: Disable swap for current session
      command: swapoff -a
 
    - name: Disable swap permanently, persist reboots
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '^/swap'
 
    - name: Copy containerd.conf to /etc/modules-load.d/
      template:
        src: templates/containerd.conf.j2
        dest: /etc/modules-load.d/containerd.conf
 
    - name: Load kernel modules overlay and br_netfilter
      command: modprobe {{ item }}
      with_items:
        - overlay
        - br_netfilter
 
    - name: Copy kubernetes.conf to /etc/sysctl.d/
      template:
        src: templates/iptables.conf.j2
        dest: /etc/sysctl.d/kubernetes.conf
      notify: Reload sysctl configuration

    - name: Create the keyrings directory with correct permissions
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key using curl
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        executable: /bin/bash

    - name: Add Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

          #    - name: Update apt cache
          #apt:
          #update_cache: yes

    - name: Install containerd.io
      apt:
        name: containerd.io
        state: present
        update_cache: yes
      ignore_errors: yes
      register: install_containerd_output

    - name: create containerd directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: adding containerd default config
      command: containerd config default
      register: containerd_default_config
      changed_when: false

    - name: Save containerd default config to a file
      copy:
        content: "{{ containerd_default_config.stdout }}"
        dest: /etc/containerd/config.toml

    - name: Modify containerd configuration
      replace:
        path: /etc/containerd/config.toml
        regexp: '.*SystemdCgroup = false$'
        replace: 'SystemdCgroup = true'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Update apt cache
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
    
    - name: Download Kubernetes GPG key
      shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
        
    - name: Ensure kubernetes.list file exists
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: touch
        mode: '0644'

    - name: Ensure kubernetes.list file exists and contains the repository line
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /'

    - name: Update apt cache
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Install Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "kubelet"
        - "kubeadm"
        - "kubectl"
        - "kubernetes-cni"

    - name: Hold packages
      command: >
        apt-mark hold {{ item }}
      with_items:
        - kubelet
        - kubeadm
        - kubectl
      ignore_errors: yes

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Enable IP forwarding
      shell: echo '1' > /proc/sys/net/ipv4/ip_forward

    - name: Run kubeadm init on master node
      when: inventory_hostname in groups['master']
      command: kubeadm init --ignore-preflight-errors=Port-10250
      ignore_errors: yes

    - name: Execute kubeadm token create command
      when: inventory_hostname in groups['master']
      command: kubeadm token create --print-join-command
      register: join_command_output

    - name: Adding worker node to the cluster
      when: inventory_hostname in groups['worker']
      command: "{{hostvars[groups['master'].0].join_command_output.stdout}} --ignore-preflight-errors=Port-10250"

    - name: Ensure /etc/kubernetes/admin.conf has the correct permissions
      when: inventory_hostname in groups['master']
      file:
        path: /etc/kubernetes/admin.conf
        mode: '0644'

    - name: Adding Network module to the cluster
      when: inventory_hostname in groups['master']
      shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
      become: false
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
    
    - name: Check Cluster status
      when: inventory_hostname in groups['master']
      shell: kubectl get nodes
      register: kubectl_output
      become: false
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"

    - name: print kubectl output
      when: inventory_hostname in groups['master']
      debug:
        msg: "{{ kubectl_output.stdout_lines  }}"

